# Generated by Django 4.2.1 on 2023-05-28 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kebabmania', '0003_alter_usuario_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='opiniones',
            name='nota',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
