# Generated by Django 4.2.1 on 2023-06-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kebabmania', '0004_opiniones_nota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(max_length=9, unique=True),
        ),
    ]
